import React from 'react';
import '../aitools.module.css';
import { useState } from 'react';

export const AiToolsAdvice = () => {
  const [response, setResponse] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  function handleFormSubmission(e) {
    e.preventDefault();
    const form = new FormData(e.target);
    const age = form.get("age");
    const currentMentalState = form.get("currentMentalState");
    const advicePrompt = form.get("advicePrompt");
    const situationOrChallenge = form.get("situationOrChallenge");
    const context = form.get("context");

    handleSubmit(age, currentMentalState, advicePrompt, situationOrChallenge, context);
  }

  async function handleSubmit(age, currentMentalState, advicePrompt, situationOrChallenge, context) {
    setIsLoading(true);
    try {
      const adviceParams = {
        age: age ? parseInt(age) : undefined,
        currentMentalState,
        advicePrompt,
        situationOrChallenge,
        context
      };

      const res = await fetch('http://localhost:3000/api/advice', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(adviceParams)
      });

      const data = await res.json();
      setResponse(data);
    } catch (error) {
      console.error("Fetch error", error);
      setResponse({ error: "Failed to generate advice" });
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>
      {!response ? (
        <div className="advice-form-container">
          <h1>Get Personalized Advice</h1>
          <p>Fill out the form below to receive customized advice for your situation.</p>

          <form onSubmit={handleFormSubmission} className="aitools_fitness">
            <label>Your Age (Optional)</label>
            <input name="age" type="number" placeholder="Enter your age" />

            <label>Current Mental State</label>
            <select name="currentMentalState" required>
              <option value="">Select your current state</option>
              <option value="calm">Calm</option>
              <option value="anxious">Anxious</option>
              <option value="stressed">Stressed</option>
              <option value="excited">Excited</option>
              <option value="confused">Confused</option>
              <option value="overwhelmed">Overwhelmed</option>
              <option value="motivated">Motivated</option>
              <option value="frustrated">Frustrated</option>
            </select>

            <label>What kind of advice are you looking for?</label>
            <input
              name="advicePrompt"
              required
              placeholder="E.g., Career guidance, relationship advice, etc."
            />

            <label>Describe your situation or challenge</label>
            <textarea
              name="situationOrChallenge"
              required
              rows={4}
              placeholder="Provide details about what you're currently facing"
            ></textarea>

            <label>Additional Context</label>
            <textarea
              name="context"
              rows={3}
              placeholder="Any relevant background information or details"
            ></textarea>

            <button type="submit" disabled={isLoading} className="submit-button">
              {isLoading ? 'Generating Advice...' : 'Get Advice'}
            </button>
          </form>
        </div>
      ) : (
        <div className="advice-response">
          <h2>Your Personalized Advice</h2>
          {response.error ? (
            <div className="error-message">{response.error}</div>
          ) : (
            <>
              <div className="advice-content">
                {typeof response === 'string' ? response : JSON.stringify(response, null, 2)}
              </div>
              <div className="disclaimer">
                Note: This advice is generated by AI and should not replace professional guidance.
              </div>
            </>
          )}
          <button onClick={() => setResponse(null)} className="reset-button">
            Ask For More Advice
          </button>
        </div>
      )}
    </div>
  );
};